{
 "title": "Controller Runtime",
 "description": "Generic dashboard for controller-runtime based processes\n(https://github.com/kubernetes-sigs/controller-runtime)\n",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": "label_values(process_cpu_seconds_total, cluster)"
   },
   {
    "name": "namespace",
    "query": "label_values(process_cpu_seconds_total{cluster=~\"$cluster\"}, namespace)"
   },
   {
    "name": "job",
    "query": "label_values(process_cpu_seconds_total{cluster=~\"$cluster\", namespace=~\"$namespace\"}, job)"
   }
  ]
 },
 "panels": [
  { "title": "Process", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (cluster, namespace, job) (\n    rate(\n        process_cpu_seconds_total{\n            cluster=~\"$cluster\",\n            namespace=~\"$namespace\",\n            job=~\"$job\"\n        }\n    [$__rate_interval])\n)\n",
     "legendFormat": "{{cluster}} - {{namespace}}\n"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (cluster, namespace, job) (\n  process_virtual_memory_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\"}\n)\n",
     "legendFormat": "virtual - {{cluster}} - {{namespace}}\n"
    },
    {
     "expr": "sum by (cluster, namespace, job) (\n  process_resident_memory_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\"}\n)\n",
     "legendFormat": "resident - {{cluster}} - {{namespace}}\n"
    },
    {
     "expr": "sum by (cluster, namespace, job) (\n  go_memstats_heap_inuse_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\"}\n)\n",
     "legendFormat": "go heap - {{cluster}} - {{namespace}}\n"
    },
    {
     "expr": "sum by (cluster, namespace, job) (\n  go_memstats_stack_inuse_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\"}\n)\n",
     "legendFormat": "go stack - {{cluster}} - {{namespace}}\n"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "sum by (cluster, namespace, job) (\n  go_goroutines{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\"}\n)\n",
     "legendFormat": "{{cluster}} - {{namespace}}\n"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by (cluster, namespace, job) (\n  go_threads{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\"}\n)\n",
     "legendFormat": "{{cluster}} - {{namespace}}\n"
    }
   ]
  },
  {
   "title": "GC Duration Mean",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (cluster, namespace, job) (\n  rate(\n    go_gc_duration_seconds_sum{\n        cluster=~\"$cluster\",\n        namespace=~\"$namespace\",\n        job=~\"$job\"\n    }\n  [$__rate_interval])\n)\n",
     "legendFormat": "{{cluster}} - {{namespace}}\n"
    }
   ]
  },
  {
   "title": "Kubernetes Client",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Workqueue Waiting Duration Over Time",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
     "targets": [
      {
       "expr": "sum by(cluster, namespace, job, le, name) (\n  rate(\n    workqueue_queue_duration_seconds_bucket{\n        cluster=~\"$cluster\",\n        namespace=~\"$namespace\",\n        job=~\"$job\"\n    }\n  [$__rate_interval])\n)\n",
       "legendFormat": "{{cluster}} - {{namespace}}\n"
      }
     ]
    },
    {
     "title": "Workqueue Waiting Duration Quantile",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.50,\n  sum by (cluster, namespace, job, le, name) (\n    rate(\n      workqueue_queue_duration_seconds_bucket{\n          cluster=~\"$cluster\",\n          namespace=~\"$namespace\",\n          job=~\"$job\"\n      }\n    [$__rate_interval])\n  )\n)\n",
       "legendFormat": "{{cluster}} - {{namespace}} - {{name}} - 50%\n"
      },
      {
       "expr": "histogram_quantile(\n  0.95,\n  sum by (cluster, namespace, job, le, name) (\n    rate(\n      workqueue_queue_duration_seconds_bucket{\n          cluster=~\"$cluster\",\n          namespace=~\"$namespace\",\n          job=~\"$job\"\n      }\n    [$__rate_interval])\n  )\n)\n",
       "legendFormat": "{{cluster}} - {{namespace}} - {{name}} - 95%\n"
      },
      {
       "expr": "sum by (cluster, namespace, job, name) (\n  rate(\n    workqueue_queue_duration_seconds_sum{\n        cluster=~\"$cluster\",\n        namespace=~\"$namespace\",\n        job=~\"$job\"\n    }\n  [$__rate_interval])\n)\n",
       "legendFormat": "{{cluster}} - {{namespace}} - {{name}} - mean\n"
      }
     ]
    },
    {
     "title": "Workqueue Depth",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(cluster, namespace, job, name) (\n  workqueue_depth{cluster=~\"$cluster\", namespace=~\"$namespace\", job=~\"$job\"}\n)\n",
       "legendFormat": "{{cluster}} - {{namespace}} - {{name}}\n"
      }
     ]
    },
    {
     "title": "Failed Requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "ceil by (cluster, namespace, job, host, method) (\n  sum(\n    increase(\n      rest_client_requests_total{\n          cluster=~\"$cluster\",\n          namespace=~\"$namespace\",\n          job=~\"$job\",\n          code=~\"^(4|5).*\"\n      }\n    [$__rate_interval])\n  )\n)\n",
       "legendFormat": "{{cluster}} - {{namespace}} - {{host}} - {{method}}\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Controller Runtime",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Reconciling Latency Over Time",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
     "targets": [
      {
       "expr": "sum by (cluster, namesapce, job,le,controller) (\n  rate(\n    controller_runtime_reconcile_time_seconds_bucket{\n        cluster=~\"$cluster\",\n        namespace=~\"$namespace\",\n        job=~\"$job\"\n    }\n  [$__rate_interval])\n)\n",
       "legendFormat": "{{cluster}} - {{namespace}}\n"
      }
     ]
    },
    {
     "title": "Reconciling Latency Quantile",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.50,\n  sum by (cluster, namespace, job, le, controller) (\n    rate(\n      controller_runtime_reconcile_time_seconds_bucket{\n          cluster=~\"$cluster\",\n          namespace=~\"$namespace\",\n          job=~\"$job\"\n      }\n    [$__rate_interval])\n  )\n)\n",
       "legendFormat": "{{cluster}} - {{namespace}} - {{name}} - 50%\n"
      },
      {
       "expr": "histogram_quantile(\n  0.95,\n  sum by (cluster, namespace, job, le, controller) (\n    rate(\n      controller_runtime_reconcile_time_seconds_bucket{\n          cluster=~\"$cluster\",\n          namespace=~\"$namespace\",\n          job=~\"$job\"\n      }\n    [$__rate_interval])\n  )\n)\n",
       "legendFormat": "{{cluster}} - {{namespace}} - {{name}} - 95%\n"
      },
      {
       "expr": "sum by (cluster, namespace, job, controller) (\n  rate(\n    controller_runtime_reconcile_time_seconds_sum{\n        cluster=~\"$cluster\",\n        namespace=~\"$namespace\",\n        job=~\"$job\"\n    }\n  [$__rate_interval])\n)\n",
       "legendFormat": "{{cluster}} - {{namespace}} - {{name}} - mean\n"
      }
     ]
    }
   ]
  }
 ]
}