apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  hub: registry.cn-hangzhou.aliyuncs.com/acejilam
  components:
    cni:
      enabled: true
    ztunnel:
      enabled: true
    ingressGateways:
      - name: istio-ingressgateway
        enabled: false
  values:
    profile: ambient

