// Copyright Istio Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// package jwt includes sample JWT Token used in e2e tests.
package jwt

const (

	// Payload {
	//  "exp": 4757607896,
	//  "iat": 1604007896,
	//  "iss": "test-issuer-1@istio.io",
	//  "nested": {
	//    "key1": [
	//      "valueA",
	//      "valueB"
	//    ],
	//    "nested-2": {
	//      "key1": [
	//        "valueA",
	//        "valueB"
	//      ]
	//    }
	//  },
	//  "sub": "sub-1"
	// }
	// Generated by: security/tools/jwt/samples/gen-jwt.py tests/common/jwt/key.pem -jwks=tests/common/jwt/jwks.json
	// --expire=3153600000 --iss=test-issuer-1@istio.io --sub=sub-1 --nestedclaim key1 valueA valueB
	// nolint: lll
	TokenIssuer1WithNestedClaims1 = "eyJhbGciOiJSUzI1NiIsImtpZCI6InRUX3c5TFJOclk3d0phbEdzVFlTdDdydXRaaTg2R3Z5YzBFS1I0Q2FRQXciLCJ0eXAiOiJKV1QifQ.eyJleHAiOjQ3NTc2MDc4OTYsImlhdCI6MTYwNDAwNzg5NiwiaXNzIjoidGVzdC1pc3N1ZXItMUBpc3Rpby5pbyIsIm5lc3RlZCI6eyJrZXkxIjpbInZhbHVlQSIsInZhbHVlQiJdLCJuZXN0ZWQtMiI6eyJrZXkxIjpbInZhbHVlQSIsInZhbHVlQiJdfX0sInN1YiI6InN1Yi0xIn0.l8p-9Yha6uAEC4iahFNHvMxeEvQmBYxegGCiBr2oJpsmKu4IxuOL9RnEQpG5C2xHgF9vBfjifo_Jl1qtMCiKMRsWoFusnNoPwbk3mUp1Y8t1mvOkVPp4roed6tM5NmhUQMyP106sru4DszS1QNfDyGtpZZny2ls5Mva-B3kxclLjswXuRb5v70YKfqpYVDtZbltZg5CD2-V6ZwJgx2ZlXCOob-7uCDyaLSRWLxS8tFMo_akdWFCxpnkGJUtS5R1nAcofX5vYSqxfcKMSJpKMluDcX859jQ9zu_eBfAjvniVP8iOuZU-JKI2GywL3x1hBfD4ebSvNiEs7jCszagIM8Q"

	// Payload {
	//  "exp": 4757608018,
	//  "iat": 1604008018,
	//  "iss": "test-issuer-1@istio.io",
	//  "nested": {
	//    "key2": "valueC",
	//    "nested-2": {
	//      "key2": "valueC"
	//    }
	//  },
	//  "sub": "sub-1"
	// }
	// Generated by: security/tools/jwt/samples/gen-jwt.py tests/common/jwt/key.pem -jwks=tests/common/jwt/jwks.json
	// --expire=3153600000 --iss=test-issuer-1@istio.io --sub=sub-1 --nestedclaim key2 valueC
	// nolint: lll
	TokenIssuer1WithNestedClaims2 = "eyJhbGciOiJSUzI1NiIsImtpZCI6InRUX3c5TFJOclk3d0phbEdzVFlTdDdydXRaaTg2R3Z5YzBFS1I0Q2FRQXciLCJ0eXAiOiJKV1QifQ.eyJleHAiOjQ3NTc2MDgwMTgsImlhdCI6MTYwNDAwODAxOCwiaXNzIjoidGVzdC1pc3N1ZXItMUBpc3Rpby5pbyIsIm5lc3RlZCI6eyJrZXkyIjoidmFsdWVDIiwibmVzdGVkLTIiOnsia2V5MiI6InZhbHVlQyJ9fSwic3ViIjoic3ViLTEifQ.dPBVaeOoMBFh9EFovHtmG2V-Bw106kUAV4GTPTVwoOaLxVUfAIpumrGX1fvEYLmtdwEkkL2CkkDdmKbsBgJBfnwg04oMeyHHrpSe5Y-8NJWGGxaBTzc7btWIbc1IPvj0vw_jIBeSqpXyW2Kd1Rc9kxK8rRuTdAeSK6oKcqg5d6kw-fC5PeiDlnuBH7F-xIaPYOHSxlKjC6TSP6-JYlQHw-uZ6rJmFwhUvc9B06dl3Xgx1W3PmYyt1e4kmHBPbwTgj1ckv8yev1JfIbciaNyQcgMf_eFwgQscHSeUY2e3v6DYAGHAQv0M6o_wweUlHfJP1juxUVA3UfpqC76NeiYipg"

	// TokenIssuer1WithCollisionResistantName
	// payload:
	//{
	//  "exp": 4837231657,
	//  "iat": 1683631657,
	//  "iss": "test-issuer-1@istio.io",
	//  "sub": "sub-1",
	//  "test-issuer-1@istio.io/nested": {
	//    "key1": "valueC",
	//    "nested-2": {
	//      "key1": "valueC"
	//    }
	//  },
	//  "test-issuer-1@istio.io/simple": "valueC"
	//}
	// Generated by: python3 security/tools/jwt/samples/gen-jwt.py tests/common/jwt/key.pem -jwks=tests/common/jwt/jwks.json
	// --expire=3153600000 --iss=test-issuer-1@istio.io --sub=sub-1
	// --claims=test-issuer-1@istio.io/simple:valueC
	// --nestedkey=test-issuer-1@istio.io/nested --nestedclaim key1 valueC
	// nolint: lll
	TokenIssuer1WithCollisionResistantName = "eyJhbGciOiJSUzI1NiIsImtpZCI6InRUX3c5TFJOclk3d0phbEdzVFlTdDdydXRaaTg2R3Z5YzBFS1I0Q2FRQXciLCJ0eXAiOiJKV1QifQ.eyJleHAiOjQ4MzcyMzE2NTcsImlhdCI6MTY4MzYzMTY1NywiaXNzIjoidGVzdC1pc3N1ZXItMUBpc3Rpby5pbyIsInN1YiI6InN1Yi0xIiwidGVzdC1pc3N1ZXItMUBpc3Rpby5pby9uZXN0ZWQiOnsia2V5MSI6InZhbHVlQyIsIm5lc3RlZC0yIjp7ImtleTEiOiJ2YWx1ZUMifX0sInRlc3QtaXNzdWVyLTFAaXN0aW8uaW8vc2ltcGxlIjoidmFsdWVDIn0.kiXEekepka92nbKNZoPrjx4oeg5OI_ILROfZ9RR02tPsaXmVAEXzfsd5foend_seEru85oLXwiBM8uFJgn8hjE9oD4wXs-xGJHpgTogBeiuzIkrWN0o6iD03tYHFKCTUY8O5B5-9NoyYiEL5pNUqPd16VwfMRg_8qaOZPBVqES-mQED8xVL_UXOlkVQEsb2QUZD_9WfkzO1JRk8m1b6gxxxN2Its1jUB-F667yUQ5tUcYbuaus5yG5sWwpAJTXWzakC2Qq6NfB5hV2fwOsVSLUvH6B7sBq6dz6W03-xFH58j_aAAF0ceJ_LsX63hqZfUOeIcbKCRFoe6Ou8cw5sRtw"

	// Payload {
	//  "exp": 1562182856,
	//  "groups": [
	//    "group-1"
	//  ],
	//  "iat": 1562182855,
	//  "iss": "test-issuer-1@istio.io",
	//  "sub": "sub-1"
	// }
	// Generated by: security/tools/jwt/samples/gen-jwt.py tests/common/jwt/key.pem -jwks=tests/common/jwt/jwks.json
	// --expire=1 --iss=test-issuer-1@istio.io --sub=sub-1 --listclaim groups "group-1"
	// nolint: lll
	TokenExpired = "eyJhbGciOiJSUzI1NiIsImtpZCI6InRUX3c5TFJOclk3d0phbEdzVFlTdDdydXRaaTg2R3Z5YzBFS1I0Q2FRQXciLCJ0eXAiOiJKV1QifQ.eyJleHAiOjE1NjIxODI4NTYsImdyb3VwcyI6WyJncm91cC0xIl0sImlhdCI6MTU2MjE4Mjg1NSwiaXNzIjoidGVzdC1pc3N1ZXItMUBpc3Rpby5pbyIsInN1YiI6InN1Yi0xIn0.o9hp0P5DS66Q7wP38wGo0AKS5HoWdHXrAUdNLnXzVC4MwU4N9o3U0PfDgWp8A7YIbDuuQAtKJyCHEJCV3JEh7Xb5Tz_12hYQcXcJ0FTA6pOXrbWRjkAVMhs3-OHiKt855s39l2OKrLwmJ3ph7LV4z8J8i-2LE2hQH18R00_dcx2agoY1VNYH2LSErBYx6e-HQlKFW8c9sQ1CHG7u4ns1I2e23A0nBlRWRUHUYIMo6sfAPWhyQWl1kpRzg6b3fyXGfUpgeEmdIPDK7MfRUZA-0epFGjvoqCwgMdEEQ-O_pH5y2qV1jPpu-9IO_FdpYhHofKMTn_ql05ys6zoIHj9Gng"
)
